sudo: enabled
language: node_js
node_js: v10.13.0

install:
 - npm install

script:
 - echo "No tests yet, but they'r coming, don't worry ;)"

before_deploy:
 - npm install
 - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/modern
  on:
    tags: true
